### ISSUE TITLE
Messages from Rollup plugins

### ISSUE THREAD

**Issue by lucascaprio** [rollup/stream#4]
I'm receiving some messages bellow when using some Rollup plugins (**rollup-plugin-babel**, **@rollup/plugin-commonjs** and **@rollup/plugin-node-resolve**).

```
The "resolveId" hook used by the output plugin babel is a build time hook and will not be run for that plugin. Either this plugin cannot be used as an output plugin, or it should have an option to configure it as an output plugin.
The "load" hook used by the output plugin babel is a build time hook and will not be run for that plugin. Either this plugin cannot be used as an output plugin, or it should have an option to configure it as an output plugin.
The "transform" hook used by the output plugin babel is a build time hook and will not be run for that plugin. Either this plugin cannot be used as an output plugin, or it should have an option to configure it as an output plugin.
The "buildStart" hook used by the output plugin node-resolve is a build time hook and will not be run for that plugin. Either this plugin cannot be used as an output plugin, or it should have an option to configure it as an output plugin.
The "resolveId" hook used by the output plugin node-resolve is a build time hook and will not be run for that plugin. Either this plugin cannot be used as an output plugin, or it should have an option to configure it as an output plugin.
The "load" hook used by the output plugin node-resolve is a build time hook and will not be run for that plugin. Either this plugin cannot be used as an output plugin, or it should have an option to configure it as an output plugin.
The "buildStart" hook used by the output plugin commonjs is a build time hook and will not be run for that plugin. Either this plugin cannot be used as an output plugin, or it should have an option to configure it as an output plugin.
The "resolveId" hook used by the output plugin commonjs is a build time hook and will not be run for that plugin. Either this plugin cannot be used as an output plugin, or it should have an option to configure it as an output plugin.
The "load" hook used by the output plugin commonjs is a build time hook and will not be run for that plugin. Either this plugin cannot be used as an output plugin, or it should have an option to configure it as an output plugin.
The "transform" hook used by the output plugin commonjs is a build time hook and will not be run for that plugin. Either this plugin cannot be used as an output plugin, or it should have an option to configure it as an output plugin.
```

My code:
```
...
return rollupStream({
    input: 'src/test.js',
    cache,
    plugins: [
        babel({
            presets: [ [ '@babel/preset-env', { modules: false } ] ],
            exclude: 'node_modules/**',
            babelrc: false
        }),
        resolve(),
        commonjs()
    ],
...
```

Apparently the plugins are working, but they are displaying these messages.

Please, can help me how to solve?

Thanks!

**Comment by shellscape** [comment]
Hey thanks for opening an issue. Unfortunately this isn't the right place to ask for support. **You also ignored the issue templates**, which is just not cool. Citing the issue templates:

> Hey there! If you need help or tech support then this is not the place to
ask. Please head to [the Rollup Gitter](https://gitter.im/rollup/rollup)
instead or post a question to https://stackoverflow.com/questions/tagged/rollupjs.

>   👉🏽 Need help or tech support? Please don't open an issue!
  Head to https://gitter.im/rollup/rollup or https://stackoverflow.com/questions/tagged/rollupjs

Apologies, but we don't have the bandwidth to service both support requests and technical issues for Rollup. Please try one of the avenues mentioned above (and in the issue templates).

**Comment by lukastaegert** [comment]
Not sure this is solely a support issue. If the code is what the user actually used, then it appears that his plugins were used as output plugins instead of input plugins, i.e. even though he added the plugins at the top-level, it behaves as if the plugins were added nested in `output`.

And he is correct:
In this line
https://github.com/rollup/stream/blob/34bda6c45f1254cc470ea5510ae7fbbc092a023e/src/index.ts#L10
you are passing the same options to `bundle.generate` that you are passing to `rollup.rollup` while you should probably be passing `options.output`.

I would see this as a serious bug as it hits everyone using non-output plugins.

**Comment by JoyceBabu** [comment]
@lukastaegert's suggestion to changing 
```
const { output } = await bundle.generate(options); 
``` 
to 
```
const { output } = await bundle.generate(options.output); 
```
worked for me. Can you please fix this? Shall I send a PR?

**Comment by JoyceBabu** [comment]
I retract my offer to send a PR, since I have no idea how to check for warnings.  And since the PR template says you will not accept PRs without tests.

**Comment by shellscape** [comment]
Fixed by #5.

**Comment by htshah** [comment]
I am still facing this issue. I am using `yarn add -D @rollup/stream` to install this package. I even tried installing this package using `npm` but got the same results.

**Comment by jsumnerPhD** [comment]
Any possibility of publishing a 1.0.1 minor version with the fix?

**Comment by andremacola** [comment]
@jsumnerPhD I just created an updated fork with the `dist` folder to temporary resolve this. Maybe you can do the same.

`yarn add https://github.com/andremacola/stream.git -D`
`npm install https://github.com/andremacola/stream.git --save-dev`

Remember to rollback when they publish an updated version on official npm

**Comment by niklaswolf** [comment]
Hey guys, there is still no patch release besides the fix being merged way back in May. Still running into this issue today. @lukastaegert when is the release of this fix planned?

**Comment by lukastaegert** [comment]
cc @shellscape who usually does these kind of releases, but I can also push out a release if he does not mind.

**Comment by shellscape** [comment]
I don't mind. I've been busy with the new baby

**Comment by niklaswolf** [comment]
@lukastaegert @shellscape 
Would be much appreciated, thanks guys 😊

**Comment by lukastaegert** [comment]
Published as 1.1.0
